/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ConfirmadosRouteImport } from './routes/confirmados'
import { Route as ConversacionesRouteImport } from './routes/conversaciones'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as IntegracionesRouteImport } from './routes/integraciones'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PlantillasRouteImport } from './routes/plantillas'
import { Route as WorkflowsRouteImport } from './routes/workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmadosRoute = ConfirmadosRouteImport.update({
  id: '/confirmados',
  path: '/confirmados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversacionesRoute = ConversacionesRouteImport.update({
  id: '/conversaciones',
  path: '/conversaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracionesRoute = IntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantillasRoute = PlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/confirmados': typeof ConfirmadosRoute
  '/conversaciones': typeof ConversacionesRoute
  '/equipo': typeof EquipoRoute
  '/integraciones': typeof IntegracionesRoute
  '/pagos': typeof PagosRoute
  '/pedidos': typeof PedidosRoute
  '/plantillas': typeof PlantillasRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/confirmados': typeof ConfirmadosRoute
  '/conversaciones': typeof ConversacionesRoute
  '/equipo': typeof EquipoRoute
  '/integraciones': typeof IntegracionesRoute
  '/pagos': typeof PagosRoute
  '/pedidos': typeof PedidosRoute
  '/plantillas': typeof PlantillasRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/confirmados': typeof ConfirmadosRoute
  '/conversaciones': typeof ConversacionesRoute
  '/equipo': typeof EquipoRoute
  '/integraciones': typeof IntegracionesRoute
  '/pagos': typeof PagosRoute
  '/pedidos': typeof PedidosRoute
  '/plantillas': typeof PlantillasRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/confirmados'
    | '/conversaciones'
    | '/equipo'
    | '/integraciones'
    | '/pagos'
    | '/pedidos'
    | '/plantillas'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/confirmados'
    | '/conversaciones'
    | '/equipo'
    | '/integraciones'
    | '/pagos'
    | '/pedidos'
    | '/plantillas'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/confirmados'
    | '/conversaciones'
    | '/equipo'
    | '/integraciones'
    | '/pagos'
    | '/pedidos'
    | '/plantillas'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ConfirmadosRoute: typeof ConfirmadosRoute
  ConversacionesRoute: typeof ConversacionesRoute
  EquipoRoute: typeof EquipoRoute
  IntegracionesRoute: typeof IntegracionesRoute
  PagosRoute: typeof PagosRoute
  PedidosRoute: typeof PedidosRoute
  PlantillasRoute: typeof PlantillasRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmados': {
      id: '/confirmados'
      path: '/confirmados'
      fullPath: '/confirmados'
      preLoaderRoute: typeof ConfirmadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversaciones': {
      id: '/conversaciones'
      path: '/conversaciones'
      fullPath: '/conversaciones'
      preLoaderRoute: typeof ConversacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integraciones': {
      id: '/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof IntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantillas': {
      id: '/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof PlantillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ConfirmadosRoute: ConfirmadosRoute,
  ConversacionesRoute: ConversacionesRoute,
  EquipoRoute: EquipoRoute,
  IntegracionesRoute: IntegracionesRoute,
  PagosRoute: PagosRoute,
  PedidosRoute: PedidosRoute,
  PlantillasRoute: PlantillasRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
